-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 15:31:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NWA
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uoc_mad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cap` (
  `id` INT NOT NULL,
  `cap_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `mobile` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`),
  INDEX `fk_company_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `type` (
  `id` INT NOT NULL,
  `type_description` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_type_company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_type_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lat/long` VARCHAR(100) NOT NULL,
  `media` VARCHAR(200) NOT NULL,
  `datetime` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `user_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `type_company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `type_id`, `type_company_id`),
  INDEX `fk_marker_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_marker_type1_idx` (`type_id` ASC, `type_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_marker_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marker_type1`
    FOREIGN KEY (`type_id` , `type_company_id`)
    REFERENCES `type` (`id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role_has_cap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_has_cap` (
  `role_id` INT NOT NULL,
  `cap_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `cap_id`),
  INDEX `fk_role_has_cap_cap1_idx` (`cap_id` ASC) VISIBLE,
  INDEX `fk_role_has_cap_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_cap_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_cap_cap1`
    FOREIGN KEY (`cap_id`)
    REFERENCES `cap` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
